#!/bin/bash
# vfos: {"abi": "1", "build_depends": [], "depends": ["python"], "local_files": {"bin/vfos": "files/bin/vfos", "config/X11/10-modesetting.conf": "files/config/X11/10-modesetting.conf", "config/X11/40-libinput.conf": "files/config/X11/40-libinput.conf", "config/dhcpcd.conf": "files/config/dhcpcd.conf", "config/firefox/mozconfig": "files/config/firefox/mozconfig", "config/firefox/policies.json": "files/config/firefox/policies.json", "config/init.d/seatd": "files/config/init.d/seatd", "config/inittab": "files/config/inittab", "config/kernel/vfos.config": "files/config/kernel/vfos.config", "config/logrotate.conf": "files/config/logrotate.conf", "config/syslog.conf": "files/config/syslog.conf", "config/wpa_supplicant.conf": "files/config/wpa_supplicant.conf", "profiles/release.json": "files/profiles/release.json", "profiles/system.json": "files/profiles/system.json", "profiles/x86-64-v1.json": "files/profiles/x86-64-v1.json", "profiles/x86-64-v3.json": "files/profiles/x86-64-v3.json", "recipes/dmenu/recipe.sh": "files/recipes/dmenu/recipe.sh", "recipes/dwm/recipe.sh": "files/recipes/dwm/recipe.sh", "recipes/grub/recipe.sh": "files/recipes/grub/recipe.sh", "recipes/hello/glibc-c23.patch": "files/recipes/hello/glibc-c23.patch", "recipes/hello/recipe.sh": "files/recipes/hello/recipe.sh", "recipes/seatd/recipe.sh": "files/recipes/seatd/recipe.sh", "recipes/st/recipe.sh": "files/recipes/st/recipe.sh", "recipes/vfos-session/recipe.sh": "files/recipes/vfos-session/recipe.sh", "recipes/vfos-tools/recipe.sh": "files/recipes/vfos-tools/recipe.sh", "recipes/xfsprogs/recipe.sh": "files/recipes/xfsprogs/recipe.sh", "recipes/xlibre/recipe.sh": "files/recipes/xlibre/recipe.sh", "sessions/vfos-session": "files/sessions/vfos-session", "sessions/vfos-session-child": "files/sessions/vfos-session-child", "vfos/__init__.py": "files/vfos/__init__.py", "vfos/boot.py": "files/vfos/boot.py", "vfos/bootstrap.py": "files/vfos/bootstrap.py", "vfos/build.py": "files/vfos/build.py", "vfos/cli.py": "files/vfos/cli.py", "vfos/common.py": "files/vfos/common.py", "vfos/image.py": "files/vfos/image.py", "vfos/installer.py": "files/vfos/installer.py", "vfos/kernel.py": "files/vfos/kernel.py", "vfos/packages.py": "files/vfos/packages.py", "vfos/recipes.py": "files/vfos/recipes.py", "vfos/release.py": "files/vfos/release.py", "vfos/session.py": "files/vfos/session.py"}, "name": "vfos-tools", "patches": [], "sources": [], "version": "0.1.0"}
set -euo pipefail
prepare() { :; }
build() { :; }
check() { python3 -c 'import ast, pathlib; [ast.parse(p.read_text()) for p in pathlib.Path("/build/recipe/files/vfos").glob("*.py")]'; }
stage() {
    site=$(python3 -c 'import sysconfig; print(sysconfig.get_path("purelib", vars={"base":"/usr","platbase":"/usr"}))')
    install -d "$DESTDIR$site/vfos"
    install -m644 "$RECIPE_DIR"/files/vfos/*.py "$DESTDIR$site/vfos/"
    install -Dm755 "$RECIPE_DIR/files/bin/vfos" "$DESTDIR/usr/bin/vfos"
    install -d "$DESTDIR/usr/share/vfos"
    cp -a "$RECIPE_DIR/files/." "$DESTDIR/usr/share/vfos/"
}
