/var/log/messages /var/log/auth.log {
    size 1M
    rotate 3
    missingok
    notifempty
    compress
    create 0640 root root
    postrotate
        /usr/bin/killall -HUP syslogd 2>/dev/null || true
    endscript
}
